### ISSUE TITLE
Smoke tester requiring Python 3.12+

### ISSUE THREAD

**Issue by stefanvodita** [apache/lucene#14556]
#14326 added a [line in scriptutil](https://github.com/apache/lucene/blob/92d79d47cbd238137ec136f6947c0c9e86003ce0/dev-tools/scripts/scriptutil.py#L26) that imports `override` from `typing`, which was [introduced in Python 3.12](https://github.com/python/cpython/issues/101561).

Running the smoke tester with 3.11, errors out like so:
```
Traceback (most recent call last):
  File "/local/home/voditas/ws/open/lucene/dev-tools/scripts/smokeTestRelease.py", line 40, in <module>
    import scriptutil
  File "/local/home/voditas/ws/open/lucene/dev-tools/scripts/scriptutil.py", line 26, in <module>
    from typing import Self, override
ImportError: cannot import name 'override' from 'typing' (/usr/local/lib/python3.11/typing.py)
```

Maybe we can make it clearer what version Python is required?

**Comment by stefanvodita** [comment]
I see we have 3.12 [configured](https://github.com/apache/lucene/blob/92d79d47cbd238137ec136f6947c0c9e86003ce0/dev-tools/scripts/pyproject.toml#L2) and at least for me that's alright. But do we have a way to warn users of the scripts that they need 3.12?

**Comment by rmuir** [comment]
I think there is a way, there is even some existing logic to do it (I suspect it has the wrong version set). Additionally, I know existing logic uses an outdated method to check the python version: because I disabled the linter violation around that.

I've also a concern that for an old python it may just fail at `pip install` phase, and never hit such a custom check. All it takes is for a library to drop support, and culturally it seems python devs are fairly aggressive on that.

We should definitely improve here though!

**Comment by msokolov** [comment]
I hit the same trying to run smoeTester with python 3.9, and got the cryptic error

**Comment by jainankitk** [comment]
Upon searching this error, saw below:

```
The ImportError: cannot import name 'Self' from 'typing' indicates that the Self type hint is not available in the typing module of your Python 3.9 environment.
The Self type was introduced in Python 3.11 (PEP 673). Since your environment uses Python 3.9, Self is not directly available in the standard typing module.
```

but did not work even with 3.11.2. Could finally get it to work with 3.12.1!

**Comment by rmuir** [comment]
I have similar problems trying to run lucene 11 with java 5!

**Comment by mikemccand** [comment]
Can't we just add a `try`/`except` around the `import`, and give a better error message ("Please upgrade to Python 3.12+" or so)?

**Comment by rmuir** [comment]
I can make it fail. if we are lazy and wait a month, 3.9 will be EOL (not even security fixes anymore) and you guys will be forced to upgrade :)
